### ISSUE TITLE
Implement login service

### ISSUE THREAD

**Issue by bachtiar-madya-p** [bachtiarmadya/IO_ASSET-V3.0#21]
refer to #20 
implement login service to `login.html`

**Api** ```POST /authentication/login```

**Sample payloads**

> {
>     "username": "jsmith",
>     "password": "P@ssw0rd"
> }

**Sample success response**

> {
>     "membercode": "jsmith",
>     "isadmin": true,
>     "levelid": "fcc139c3-2b83-5141-8cfb-3fe6f02d8c16",
>     "departmentid": "fcc139c3-2b83-5141-8cfb-3fe6f02d8c16",
>     "description": "Administrator",
>     "userid": "d8485577-68b6-50aa-b10b-6847e3d00671",
>     "membername": "John Smith",
>     "email": "bmp@ic.sg",
>     "imageaddress": "/qwert/asdf/zxcv.png",
>     "username": "jsmith",
>     "memberid": "d8485577-68b6-50aa-b10b-6847e3d00671",
>     "session-jwt": "token-here"
> }

**Sample error response**

> {
>     "reason": "wrong_username_or_password",
>     "code": 401,
>     "message": "Wrong Username or Password"
> }

**Comment by alvirayusnia2** [comment]
is this a template project ?


Pada tanggal Sen, 17 Feb 2020 03:49, Bachtiar Madya Permadi <
notifications@github.com> menulis:

**Comment by bachtiar-madya-p** [comment]
??
