### ISSUE TITLE
Revamp Application UI

### ISSUE THREAD

**Issue by bachtiar-madya-p** [bachtiarmadya/IO_ASSET-V3.0#42]
<img width="1920" alt="Screen Shot 2020-03-19 at 03 46 45" src="https://user-images.githubusercontent.com/15031909/77008605-07344400-6999-11ea-9e96-deb3844bb186.png">

<img width="1920" alt="Screen Shot 2020-03-19 at 04 21 24" src="https://user-images.githubusercontent.com/15031909/77008916-9a6d7980-6999-11ea-9173-c1cbdc95c8a9.png">

**Comment by muhammadZaahid** [comment]
![gambar](https://user-images.githubusercontent.com/60879876/77132746-0384e800-6a93-11ea-91d6-4c819fffe0db.png)

**Comment by muhammadZaahid** [comment]
![gambar](https://user-images.githubusercontent.com/60879876/77132782-244d3d80-6a93-11ea-886e-816780b07782.png)
