### ISSUE TITLE
asset master - remove item

### ISSUE THREAD

**Issue by bachtiar-madya-p** [bachtiarmadya/IO_ASSET-V3.0#59]
remove `Asset Code :` from edit modals
<img width="1720" alt="Screen Shot 2020-03-19 at 04 40 01" src="https://user-images.githubusercontent.com/15031909/77010152-d7d30680-699b-11ea-9bac-6573d81eda2e.png">

**Comment by Tatacantika** [comment]
![image](https://user-images.githubusercontent.com/60879799/77092415-64350600-6a3c-11ea-9611-42614cab4172.png)
