### ISSUE TITLE
remove register asset button

### ISSUE THREAD

**Issue by bachtiar-madya-p** [bachtiarmadya/IO_ASSET-V3.0#60]
remove the buttons
<img width="1720" alt="Screen Shot 2020-03-19 at 04 46 20" src="https://user-images.githubusercontent.com/15031909/77010619-b6264f00-699c-11ea-8d70-409f3fe5b1c5.png">

**Comment by Tatacantika** [comment]
![image](https://user-images.githubusercontent.com/60879799/77089679-b411ce00-6a38-11ea-9e97-85211207f0b0.png)
